// <auto-generated />
using System;
using Examen_final_desarrollo_web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen_final_desarrollo_web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Examen_final_desarrollo_web.Models.Clinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinicas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Clínica General"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Clínica de Pediatría"
                        });
                });

            modelBuilder.Entity("Examen_final_desarrollo_web.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentoIdentidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentoIdentidad = "1234567890101",
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            DocumentoIdentidad = "9876543210101",
                            Nombre = "María López"
                        });
                });

            modelBuilder.Entity("Examen_final_desarrollo_web.Models.ReasignacionTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NuevaClinicaId")
                        .HasColumnType("int");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NuevaClinicaId");

                    b.HasIndex("TurnoId");

                    b.ToTable("ReasignacionesTurnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaHora = new DateTime(2025, 1, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Motivo = "Clínica saturada",
                            NuevaClinicaId = 2,
                            TurnoId = 1
                        });
                });

            modelBuilder.Entity("Examen_final_desarrollo_web.Models.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Turnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicaId = 1,
                            Estado = "Pendiente",
                            FechaHora = new DateTime(2025, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            PacienteId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClinicaId = 2,
                            Estado = "Pendiente",
                            FechaHora = new DateTime(2025, 1, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            PacienteId = 2
                        });
                });

            modelBuilder.Entity("Examen_final_desarrollo_web.Models.ReasignacionTurno", b =>
                {
                    b.HasOne("Examen_final_desarrollo_web.Models.Clinica", "NuevaClinica")
                        .WithMany()
                        .HasForeignKey("NuevaClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Examen_final_desarrollo_web.Models.Turno", "Turno")
                        .WithMany("Reasignaciones")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NuevaClinica");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("Examen_final_desarrollo_web.Models.Turno", b =>
                {
                    b.HasOne("Examen_final_desarrollo_web.Models.Clinica", "Clinica")
                        .WithMany("Turnos")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examen_final_desarrollo_web.Models.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Examen_final_desarrollo_web.Models.Clinica", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Examen_final_desarrollo_web.Models.Paciente", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Examen_final_desarrollo_web.Models.Turno", b =>
                {
                    b.Navigation("Reasignaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
